Update for one-apps 6.8.1
OpenNebula/marketplace pull request #91
Opened 2024-01-31 15:29 UTC by xorel

Preferably, don't squash commits

2024-01-31 15:58 UTC, sk4zuzu requested changes

2024-01-31 15:58 UTC, sk4zuzu commented on appliances/OneKE_1.27/8285d732-0741-4623-ba9e-4eacd2421e91.yaml
> +os-release: '3.14'
```suggestion
os-release: '3.18'
```
:thinking:

2024-01-31 17:54 UTC, sk4zuzu approved these changes
LGTM

2024-02-01 09:43 UTC, rsmontero approved these changes

2024-02-01 09:45 UTC, merged